// https://cloud.google.com/speech-to-text/docs/languages?hl=ja

let h_all = {
  'Hacerlo': ['es-ES', 'できる'],
  'Halo': ['es-ES', '（太陽・月の）暈(かさ)、ハロー'],
  'Haine': ['fr-FR', '憎しみ、憎悪、嫌悪'],
  'Hands': ['lang', '意味'],
  'Håndskes': ['da-DK', '手袋'],
  'Happen': ['en-US', '起こる'],
  'Happening': ['en-US', '出来事'],
  'Happy': ['en-GB', '幸せな'],
  'Happily': ['en-GB', '愉快に、うまく'],
  'Happiness': ['en-GB', '幸福、幸せ'],
  'Harmony': ['en-GB', '調和、ハーモニー'],
  'Have': ['da-DK', '公園'],
  'Haze': ['en-GB', 'もうろう'],
  'Heart': ['en-GB', '心臓'],
  'Hearth': ['en-GB', '炉床、家庭'],
  'Heal': ['en-GB', 'いやす、治す'],
  'Healthy': ['en-GB', '健康な、健全な'],
  'Heartful': ['ja-JP', '心温まる'],
  'Here': ['en-GB', 'ここ、ここに'],
  'Heroico': ['es-ES', '英雄的な'],
  'Held': ['en-GB', '開催'],
  'Helpful': ['en-US', '役立つ'],
  'Hint': ['ja-JP', 'ヒント'],
  'Hipo': ['es-ES', 'しゃっくり'],
  'Home': ['en-GB', '家'],
  'Hold': ['en-US', '手に持つ、握る'],
  'Holding': ['en-GB', '保持、所有権、保有地'],
  'Holiness': ['en-US', '神聖'],
  'Honest': ['en-GB', '正直'],
  'Honestly': ['en-GB', '正直に、率直に'],
  'Homie': ['en-US', '仲間、親友'],
  'Horizon': ['en-GB', '地平線、水平線'],
  'Hue': ['en-GB', '色合い、色調'],
  'Human': ['en-GB', '人の、人間の'],
  'Humor': ['ja-JP', 'ユーモア'],
  'Hydro': ['el-GR', '水力']
}