// https://cloud.google.com/speech-to-text/docs/languages?hl=ja

let e_all = {
  'Ease': ['en-GB', '簡易、気楽'],
  'Easy': ['en-GB', '容易な、ゆったりした'],
  'Earth': ['en-GB', '地球'],
  'Echo': ['en-GB', 'エコー、反響'],
  'Egg': ['en-GB', '卵'],
  /*
  'Elástica': ['lang', '意味'],
  'Elastic': ['lang', '意味'],
  'Elegant': ['lang', '意味'],
  'Elegy': ['lang', '意味'],
  'Elementary': ['lang', '意味'],
  'Eller': ['lang', '意味'],
  'Else': ['lang', '意味'],
  'Elskede': ['lang', '意味'],
  'Elusive': ['lang', '意味'],
  'Elusivo': ['lang', '意味'],
  'Embarrassing': ['lang', '意味'],
  'Emergent': ['lang', '意味'],
  'Emmanuelle': ['lang', '意味'],
  'Ember': ['lang', '意味'],
  'Embraced': ['lang', '意味'],
  'Emotionally': ['lang', '意味'],
  'Emo': ['lang', '意味'],
  'Empathy': ['lang', '意味'],
  'Enchanted': ['lang', '意味'],
  'Energetic': ['lang', '意味'],
  'Energy': ['lang', '意味'],
  'Entierro': ['lang', '意味'],
  'Enjoy': ['lang', '意味'],
  'Entrancing': ['lang', '意味'],
  'Enthusiastic': ['lang', '意味'],
  'Epitaph': ['lang', '意味'],
  'Equipment': ['lang', '意味'],
  'Eroding': ['lang', '意味'],
  'Erratic': ['lang', '意味'],
  'Essentially': ['lang', '意味'],
  'Estatua': ['lang', '意味'],
  'Euphoria': ['lang', '意味'],
  'Exercise': ['lang', '意味'],
  'Experimental': ['lang', '意味'],
  'Extraordinary': ['lang', '意味'],
  'Every': ['lang', '意味'],
  'Everything': ['lang', '意味'],
  'Evil': ['lang', '意味'],
  'Exacto': ['lang', '意味'],
  'Existing': ['lang', '意味'],
  'Exhumation': ['lang', '意味'],
  */
};
