// https://cloud.google.com/speech-to-text/docs/languages?hl=ja

let e_all = {
  'Ease': ['en-GB', '簡易、気楽'],
  'Easy': ['en-GB', '容易な、ゆったりした'],
  'Earth': ['en-GB', '地球'],
  'Echo': ['en-GB', 'エコー、反響'],
  'Egg': ['en-GB', '卵'],
  'Elástica': ['it-IT', '柔軟に、しなやかに'],
  'Elegant': ['en-GB', '上品な、優雅な'],
  'Elegy': ['en-US', '哀歌'],
  'Elementary': ['en-GB', '初歩的な'],
  'Eller': ['no-NO', 'か、または'],
  'Else': ['en-GB', '他の'],
  'Elskede': ['da-DK', '愛した'],
  'Elusivo': ['es-ES', 'とらえどころのない'],
  'Embarrassing': ['en-GB', '恥ずかしい'],
  'Ember': ['en-US', '残り火'],
  'Embraced': ['en-GB', '受け入れられる'],
  'Emotionally': ['en-GB', '感情的に'],
  'Empathy': ['en-GB', '共感、感情移入'],
  'Enchanted': ['en-US', '魅惑の'],
  'Energetic': ['en-US', '活動的な'],
  'Energy': ['en-GB', '元気、活力、精力'],
  'Entierro': ['es-ES', '埋葬'],
  'Enjoy': ['en-GB', '楽しむ'],
  'Entrancing': ['en-US', '魅了する'],
  'Enthusiastic': ['en-US', '熱狂的'],
  'Epitaph': ['en-US', '墓碑銘'],
  'Equipment': ['en-US', '設備、備品'],
  'Eroding': ['en-GB', '浸食する'],
  'Erratic': ['en-GB', '不安定な'],
  'Essentially': ['en-GB', '本質的に'],
  'Estatua': ['es-ES', '像、彫像'],
  'Euphoria': ['en-US', '多幸感'],
  'Exercise': ['es-ES', '運動'],
  'Extraordinary': ['en-US', '異常な、並外れた'],
  'Every': ['en-GB', 'あらゆる、全ての'],
  'Everything': ['en-US', '全てのもの'],
  'Exacto': ['es-ES', '正確な、正しい'],
  'Existing': ['en-GB', '現存する、現在の'],
  'Exhumation': ['en-US', '埋められていたもの（特に死体）を地面から掘り出す行為']
}