// https://cloud.google.com/speech-to-text/docs/languages?hl=ja

let h_all = {
  'Hacerlo': ['es-MX', 'できる'],
  'Halo': ['es-MX', '（太陽・月の）暈(かさ)、ハロー'],
  'Haine': ['fr-FR', '憎しみ、憎悪、嫌悪'],
  'Hands': ['lang', '意味'],
  'Håndskes': ['da-DK', '手袋'],
  'Happen': ['en-US', '起こる'],
  'Happening': ['en-US', '出来事'],
  'Happy': ['en-GB', '幸せな'],
  'Happily': ['en-GB', '愉快に、うまく'],
  'Happiness': ['en-GB', '幸福、幸せ'],
  'Harmony': ['en-GB', '調和、ハーモニー'],
  'Have': ['da-DK', '公園'],
  'Haze': ['en-GB', 'もうろう'],
  'Heart': ['en-GB', '心臓'],
  'Hearth': ['en-GB', '炉床、家庭'],
  'Heal': ['en-GB', 'いやす、治す'],
  'Healthy': ['en-GB', '健康な、健全な'],
  'Heartful': ['ja-JP', '心温まる'],
  'Here': ['en-GB', 'ここ、ここに'],
  /*
  'Heroico': ['lang', '意味'],
  'Held': ['lang', '意味'],
  'Helpful': ['lang', '意味'],
  'Hint': ['lang', '意味'],
  'Hipo': ['lang', '意味'],
  'Home': ['lang', '意味'],
  'Hold': ['lang', '意味'],
  'Holding': ['lang', '意味'],
  'Holiness': ['lang', '意味'],
  'Honest': ['lang', '意味'],
  'Honestly': ['lang', '意味'],
  'Homie': ['lang', '意味'],
  'Horizon': ['lang', '意味'],
  'Hue': ['lang', '意味'],
  'Human': ['lang', '意味'],
  'Humor': ['lang', '意味'],
  'Hydro': ['lang', '意味'],
  */
};
