// https://cloud.google.com/speech-to-text/docs/languages?hl=ja

let p_all = {
  'Pan': ['fr-FR', '部分、面・一面'],
  'Paradise': ['en-GB', '楽園'],
  'Pasible': ['es-ES', '感受性の強い、傷つきやすい'],
  'Passion': ['en-GB', ' 情熱、熱情'],
  'Patient': ['en-GB', '忍耐強い、我慢強い'],
  'Pradera': ['es-ES', '草原'],
  'Pacífico': ['es-ES', '平和的な人'],
  'Particule': ['fr-FR', '微粒子'],
  'Participatory': ['en-GB', '参加型'],
  'Palabras': ['es-ES', '語'],
  'Palindrome': ['en-GB', '回文'],
  'Peace': ['en-US', '平和'],
  'Peaceful': ['en-US', '平和な、平和的な'],
  'Peacefully': ['en-US', '平和に、穏やかに'],
  'Peach': ['en-US', '桃、すてきな人'],
  'Pearl': ['en-US', '真珠、貴重なもの、逸品'],
  'Pebble': ['en-GB', '小石、小さな玉石'],
  'Pensive': ['en-GB', 'もの思わしげな、憂いに沈む'],
  'Pentagon': ['en-US', '五角形'],
  'People': ['en-GB', '人々'],
  'Perchance': ['en-GB', 'おそらくは、偶然に'],
  'Perennial': ['en-GB', '四季を通じて続く、永久の'],
  'Pero': ['es-ES', 'しかし・それにしても、ねえ'],
  'Petit': ['fr-FR', '小さい、ささいな'],
  'Petunia': ['pt-BR', 'ペチュニア'],
  'Piel': ['es-ES', '皮膚、皮'],
  'Piezas': ['es-ES', '一個、部品'],
  'Pil': ['da-DK', '矢、柳'],
  'Play': ['en-GB', '遊ぶ、する'],
  'Powerful': ['en-GB', '強い、強力な'],
  'Poetic': ['en-GB', '詩的な'],
  'Porre': ['it-IT', '置く、載せる、設定する'],
  'Pose': ['en-GB', '姿勢、ポーズ'],
  'Possible': ['en-GB', '可能な'],
  'Possibly': ['en-US', 'もしかすると、ひょっとすると'],
  'Practical': ['en-US', '現実的な、実用的な'],
  'Pretty': ['en-US', 'とても、かわいい'],
  'Préférés': ['fr-FR', 'お気に入りの'],
  'Prender': ['es-ES', '捕らえる、つかむ'],
  'Preocupar': ['es-ES', '心配させる、不安にさせる'],
  'Protected': ['en-US', '保護されている、守られている'],
  'Proyecto': ['es-ES', 'プロジェクト'],
  'Purple': ['en-US', '紫(色)の、高位の・華麗な'],
  'Pursed': ['en-US', '口［唇］をすぼめて']
}