// https://cloud.google.com/speech-to-text/docs/languages?hl=ja

let p_all = {
  'Pan': ['lang', '意味'],
  'Paradise': ['en-GB', '楽園'],
  'Pasible': ['es-MX', '感受性の強い，傷つきやすい'],
  'Passion': ['en-GB', ' 情熱、熱情'],
  'Patient': ['en-GB', '忍耐強い、我慢強い'],
  'Pradera': ['es-MX', '草原'],
  'Pacífico': ['es-MX', '平和的な人'],
  'Particule': ['fr-FR', '微粒子'],
  'Participatory': ['en-GB', '参加型'],
  'Palabras': ['es-MX', '語'],
  'Palindrome': ['en-GB', '回文'],
  'Peace': ['en-US', '平和'],
  'Peaceful': ['en-US', '平和な、平和的な'],
  'Peacefully': ['en-US', '平和に、穏やかに'],
  'Peach': ['en-US', '桃、すてきな人'],
  'Pearl': ['en-US', '真珠、貴重なもの、逸品'],
  'Pebble': ['en-GB', '小石、小さな玉石'],
  'Pensive': ['en-GB', 'もの思わしげな、憂いに沈む'],
  'Pentagon': ['en-US', '五角形'],
  'People': ['en-GB', '人々'],
  'Perchance': ['en-GB', 'おそらくは、偶然に'],
  'Perennial': ['en-GB', '四季を通じて続く、永久の'],
  'Pero': ['es-MX', 'しかし・それにしても、ねえ'],
  'Petit': ['fr-FR', '小さい、ささいな'],
  'Petunia': ['pt-BR', 'ペチュニア'],
  'Piel': ['es-MX', '皮膚、皮'],
  'Piezas': ['es-MX', '一個、部品'],
  /*
  'Pil': ['lang', '意味'],
  'Play': ['en-GB', '遊ぶ、する'],
  'Powerful': ['en-GB', '強い、強力な'],
  'Poetic': ['en-GB', '詩的な'],
  'Porre': ['lang', '意味'],
  'Pose': ['lang', '意味'],
  'Possible': ['lang', '意味'],
  'Possibly': ['lang', '意味'],
  'Practical': ['lang', '意味'],
  'Pretty': ['lang', '意味'],
  'Préférés': ['lang', '意味'],
  'Prender': ['lang', '意味'],
  'Preocupo': ['lang', '意味'],
  'Protected': ['lang', '意味'],
  'Proyecto': ['lang', '意味'],
  'Purple': ['lang', '意味'],
  'Pursed': ['lang', '意味'],
  */
};
