// https://cloud.google.com/speech-to-text/docs/languages?hl=ja

let u_all = {
  'Ufano': ['es-MX', '誇り'],
  'Ultralight': ['en-US', '超軽量'],
  'Ultra-nice': ['en-US', '超素敵'],
  'Una': ['es-MX', '女性名詞の前に付ける不定冠詞'],
  'Unafraid': ['en-GB', '恐れがない、平然として'],
  'Unconditional': ['en-US', '無条件の、絶対的な'],
  'Understand': ['en-GB', '理解する'],
  'Understanding': ['en-GB', '理解、了解'],
  'Underjordisk': ['da-DK', '地下'],
  'Underwater': ['en-GB', '水中'],
  'Undo': ['en-US', '元に戻す、結果を台なしにする'],
  'Unfolded': ['en-GB', '展開した、打ち明けた、開けた'],
  'Unity': ['en-GB', '協同，結束 '],
  'Unique': ['en-GB', '独特な、ユニーク'],
  'Universe': ['en-GB', '宇宙、万物'],
  'Untumbling': ['en-US', 'ほどける'],
  'Unusual': ['en-GB', '普通でない、珍しい'],
  'Up to': ['en-GB', '…まで(に)、…に至るまで'],
  'Update': ['en-GB', '更新'],
  'Upon': ['en-GB', '上で；そのうえに、に際し；にあたり'],
  'Urbanity': ['en-GB', '上品、都会風'],
  'Urkraft': ['da-DK', '元来の、自然な'],
  'Us': ['en-US', 'わたしたち'],
  'Usage': ['en-GB', '利用、使用法'],
  'Usual': ['en-US', 'いつもの、普通'],
  'Useful': ['en-US', '役に立つ'],
  'Usefully': ['en-US', '役に立つように、有効に'],
  'Utopia': ['en-GB', 'ユートピア'],
};
